

const data = {
 /*  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ], */
  products: [
    {
      name: 'Recliner Chair Wood',
      slug: 'Free-Chair',
      category: 'Chairs',
      image: '/images/sopa.png',
      price: 299,
      brand: 'Recliner Chair Wood',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Recliner Chair Wood',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Timber Dide Padded',
      slug: 'Chair',
      category: 'Chairs',
      image: '/images/roking.png',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Colored Woode',
      slug: 'simple chair',
      category: 'Chairs',
      image: '/images/rocking-chair.png',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular chair',
    },
    {
      name: 'Blank Bamboo Wicker',
      slug: 'Bamboo Wicker',
      category: 'chairs',
      image: '/images/image 147.png',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking chair',
    },
    {
      name: 'Isolated Wooden Rock',
      slug: 'Wooden Rock',
      category: 'Chairs',
      image: '/images/image 148.png',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular chair',
    },
    {
      name: 'Minimal Empty Rocking',
      slug: 'Empty Rocking',
      category: 'Chairs',
      image: '/images/image 149.png',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular chair',
    },
  ],
}

export default data