import { Product } from "./ProductModel";

const data: { products: Product[] } = {
  products: [
    {
      id: 1,
      name: "Recliner Chair Wood",
      offerPercent: 20,
      slug: "Free-Chair",
      categoryId: 1,
      image: "/images/sopa.png",
      price: 299,
      brand: "Recliner Chair Wood",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A Recliner Chair Wood",
      banner: "/images/banner1.jpg",
    },
    {
      id: 2,
      name: "Timber Dide Padded",
      offerPercent: 20,
      slug: "Chair",
      categoryId: 2,
      image: "/images/roking.png",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
      banner: "/images/banner2.jpg",
    },
    {
      id: 3,
      name: "Colored Woode",
      offerPercent: 20,
      slug: "simple chair",
      categoryId: 3,
      image: "/images/rocking-chair.png",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "A popular chair",
    },
    {
      id: 4,
      name: "Blank Bamboo Wicker",
      offerPercent: 20,
      slug: "Bamboo Wicker",
      categoryId: 1,
      image: "/images/image 147.png",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Smart looking chair",
    },
    {
      id: 5,
      name: "Isolated Wooden Rock",
      offerPercent: 20,
      slug: "Wooden Rock",
      categoryId: 1,
      image: "/images/image 148.png",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "A popular chair",
    },
    {
      id: 6,
      name: "Minimal Empty Rocking",
      offerPercent: 20,
      slug: "Empty Rocking",
      categoryId: 2,
      image: "/images/image 149.png",
      price: 75,
      brand: "Casely",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "A popular chair",
    },
  ],
};

export default data;
